spring.application.name=OrderCraft_Backend



server.port=${PORT:8094}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Papercut
spring.mail.host=localhost
spring.mail.port=25
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false


#PaymentGateway

cashfree.client.id=1223
cashfree.client.secret=kcdbckb221111111
